// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vm_vlsit_apbdec__Syms.h"


VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_init_sub__TOP__0(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_init_sub__TOP__0\n"); );
    Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("m_vlsit_apbdec_tb", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+139,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+140,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+141,0,"WRITE_STROBE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"m_paddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+12,0,"m_pwdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"m_prdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"m_pwrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"m_psel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"m_penable",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"m_pready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"m_pslverr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"m_pstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+20,0,"m_pprot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+21,0,"o_psel_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"o_paddr_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"o_pwdata_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+23,0,"i_pready_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"i_pslverr_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+25,0,"i_prdata_uart",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+26,0,"o_psel_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+27,0,"o_paddr_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+12,0,"o_pwdata_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+28,0,"i_pready_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"i_pslverr_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+30,0,"i_prdata_i2c",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+31,0,"o_psel_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"o_paddr_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+12,0,"o_pwdata_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+33,0,"i_pready_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"i_pslverr_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+35,0,"i_prdata_spi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+36,0,"o_psel_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+37,0,"o_paddr_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+12,0,"o_pwdata_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+38,0,"i_pready_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"i_pslverr_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"i_prdata_can",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+41,0,"o_psel_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"o_paddr_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"o_pwdata_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+42,0,"i_pready_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"i_pslverr_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"i_prdata_pwm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+45,0,"o_psel_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+46,0,"o_paddr_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+12,0,"o_pwdata_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+47,0,"i_pready_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"i_pslverr_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+49,0,"i_prdata_gyro",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("u_can_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+142,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+37,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+40,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+146,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+142,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+142,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+147,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+50,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+51,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+53,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+54,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+55,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+56,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+57,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+57,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+58,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+59,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_gyro_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+149,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+46,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+45,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+150,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+149,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+149,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+151,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+60,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+61,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+63,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+64,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+66,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+67,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+67,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+68,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+69,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_i2c_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+152,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+27,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+30,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+153,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+152,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+152,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+154,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("dmem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+70+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+86,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+87,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+89,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+90,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+92,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+93,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+93,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+94,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+95,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_m_vlsit_apbdec", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+11,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+13,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"o_paddr_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"o_pwdata_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+21,0,"o_psel_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_uart",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"i_pready_uart",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"i_pslverr_uart",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+25,0,"i_prdata_uart",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"o_paddr_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+12,0,"o_pwdata_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+26,0,"o_psel_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_i2c",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"i_pready_i2c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"i_pslverr_i2c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+30,0,"i_prdata_i2c",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+32,0,"o_paddr_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+12,0,"o_pwdata_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+31,0,"o_psel_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_spi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"i_pready_spi",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"i_pslverr_spi",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+35,0,"i_prdata_spi",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,0,"o_paddr_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 14,0);
    tracep->declBus(c+12,0,"o_pwdata_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+36,0,"o_psel_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_can",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"i_pready_can",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"i_pslverr_can",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"i_prdata_can",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"o_paddr_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"o_pwdata_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+41,0,"o_psel_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_pwm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"i_pready_pwm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"i_pslverr_pwm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"i_prdata_pwm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+46,0,"o_paddr_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+12,0,"o_pwdata_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"o_pstrb_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+45,0,"o_psel_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"o_pwrite_gyro",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"i_pready_gyro",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"i_pslverr_gyro",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+49,0,"i_prdata_gyro",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+96,0,"w_slave_uart_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"w_slave_i2c_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"w_slave_spi_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"w_slave_can_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"w_slave_pwm_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+101,0,"w_slave_gyro_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_master_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+155,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"o_paddr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+12,0,"o_pwdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"i_prdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"o_pwrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"o_psel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"o_penable",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"i_pready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"o_pstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+20,0,"o_pprot",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+102,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+138,0,"next_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+103,0,"trans_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+2,0,"req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+3,0,"req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+5,0,"req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+6,0,"req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+104,0,"read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_pwm_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+156,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+157,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+156,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+156,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+158,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->declBus(c+106,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+107,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+109,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+110,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+112,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+113,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+113,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+114,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+115,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_spi_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+159,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+160,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+159,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+159,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+161,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 12,0);
    tracep->declBus(c+116,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+117,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+119,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+120,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+122,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+123,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+123,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+125,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("u_uart_slave_bfm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+156,0,"PARA_ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+143,0,"PARA_DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+144,0,"PARA_APB_WAIT_STATES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+136,0,"i_clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"i_rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"i_paddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,0,"i_pwdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"o_prdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+14,0,"i_pwrite",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"i_psel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"i_penable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"o_pready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"o_pslverr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"i_pstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,0,"i_pprot",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+157,0,"PARA_MEM_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+156,0,"PARA_DMEM_ADDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+156,0,"PARA_IDX_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+158,0,"PARA_MEM_DEPTH_U",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 8,0);
    tracep->declBus(c+126,0,"apb_wait_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+127,0,"apb_req_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"apb_req_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+129,0,"apb_req_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+130,0,"apb_req_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"apb_req_strb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+132,0,"apb_req_prot",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+133,0,"apb_req_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+133,0,"apb_req_word_idx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+148,0,"apb_addr_in_range",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+134,0,"apb_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("apb_slave_seq", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+135,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+7,0,"v_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+148,0,"PSLVERR_VAL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"test_num",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+9,0,"test_pass",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+10,0,"test_fail",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_init_top(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_init_top\n"); );
    Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vm_vlsit_apbdec___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vm_vlsit_apbdec___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vm_vlsit_apbdec___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_register(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_register\n"); );
    Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vm_vlsit_apbdec___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vm_vlsit_apbdec___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vm_vlsit_apbdec___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vm_vlsit_apbdec___024root__trace_cleanup, vlSelf);
    }

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_const_0_sub_0(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd::Buffer* bufp);

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_const_0\n"); );
        // Init
        Vm_vlsit_apbdec___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vm_vlsit_apbdec___024root*>(voidSelf);

        Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;

        // Body
        Vm_vlsit_apbdec___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
    }

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_const_0_sub_0(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_const_0_sub_0\n"); );
        Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
        auto& vlSelfRef = std::ref(*vlSelf).get();
        // Init
        uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);

        // Body
        bufp->fullIData(oldp+139,(0x00000018U),32);
        bufp->fullIData(oldp+140,(0x00000020U),32);
        bufp->fullIData(oldp+141,(4U),32);
        bufp->fullIData(oldp+142,(0x0000000fU),32);
        bufp->fullIData(oldp+143,(0x00000020U),32);
        bufp->fullIData(oldp+144,(0U),32);
        bufp->fullCData(oldp+145,(0U),3);
        bufp->fullIData(oldp+146,(0x00008000U),32);
        bufp->fullSData(oldp+147,(0x8000U),16);
        bufp->fullBit(oldp+148,(1U));
        bufp->fullIData(oldp+149,(0x0000000aU),32);
        bufp->fullIData(oldp+150,(0x00000400U),32);
        bufp->fullSData(oldp+151,(0x0400U),11);
        bufp->fullIData(oldp+152,(4U),32);
        bufp->fullIData(oldp+153,(0x00000010U),32);
        bufp->fullCData(oldp+154,(0x10U),5);
        bufp->fullIData(oldp+155,(0x00000018U),32);
        bufp->fullIData(oldp+156,(8U),32);
        bufp->fullIData(oldp+157,(0x00000100U),32);
        bufp->fullSData(oldp+158,(0x0100U),9);
        bufp->fullIData(oldp+159,(0x0000000cU),32);
        bufp->fullIData(oldp+160,(0x00001000U),32);
        bufp->fullSData(oldp+161,(0x1000U),13);
    }

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_full_0_sub_0(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd::Buffer* bufp);

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_full_0\n"); );
        // Init
        Vm_vlsit_apbdec___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vm_vlsit_apbdec___024root*>(voidSelf);

        Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;

        // Body
        Vm_vlsit_apbdec___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
    }

    VL_ATTR_COLD void Vm_vlsit_apbdec___024root__trace_full_0_sub_0(Vm_vlsit_apbdec___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
        VL_DEBUG_IF(VL_DBG_MSGF("+    Vm_vlsit_apbdec___024root__trace_full_0_sub_0\n"); );
        Vm_vlsit_apbdec__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
        auto& vlSelfRef = std::ref(*vlSelf).get();
        // Init
        uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);

        // Body
        bufp->fullIData(oldp+1,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_addr),24);
        bufp->fullIData(oldp+2,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_wdata),32);
        bufp->fullBit(oldp+3,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_write));
        bufp->fullCData(oldp+4,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_strb),4);
        bufp->fullCData(oldp+5,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_prot),3);
        bufp->fullBit(oldp+6,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__req_valid));
        bufp->fullIData(oldp+7,(vlSelfRef.m_vlsit_apbdec_tb__DOT__unnamedblk1__DOT__v_rdata),32);
        bufp->fullIData(oldp+8,(vlSelfRef.m_vlsit_apbdec_tb__DOT__unnamedblk1__DOT__test_num),32);
        bufp->fullIData(oldp+9,(vlSelfRef.m_vlsit_apbdec_tb__DOT__unnamedblk1__DOT__test_pass),32);
        bufp->fullIData(oldp+10,(vlSelfRef.m_vlsit_apbdec_tb__DOT__unnamedblk1__DOT__test_fail),32);
        bufp->fullIData(oldp+11,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr),24);
        bufp->fullIData(oldp+12,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pwdata),32);
        bufp->fullIData(oldp+13,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_prdata),32);
        bufp->fullBit(oldp+14,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pwrite));
        bufp->fullBit(oldp+15,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_psel));
        bufp->fullBit(oldp+16,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_penable));
        bufp->fullBit(oldp+17,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pready));
        bufp->fullBit(oldp+18,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pslverr));
        bufp->fullCData(oldp+19,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pstrb),4);
        bufp->fullCData(oldp+20,(vlSelfRef.m_vlsit_apbdec_tb__DOT__m_pprot),3);
        bufp->fullBit(oldp+21,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_uart));
        bufp->fullCData(oldp+22,((0x000000ffU & vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)),8);
        bufp->fullBit(oldp+23,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_uart));
        bufp->fullBit(oldp+24,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_uart));
        bufp->fullIData(oldp+25,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_uart),32);
        bufp->fullBit(oldp+26,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_i2c));
        bufp->fullCData(oldp+27,((0x0000000fU & vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)),4);
        bufp->fullBit(oldp+28,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_i2c));
        bufp->fullBit(oldp+29,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_i2c));
        bufp->fullIData(oldp+30,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_i2c),32);
        bufp->fullBit(oldp+31,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_spi));
        bufp->fullSData(oldp+32,((0x00000fffU & vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)),12);
        bufp->fullBit(oldp+33,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_spi));
        bufp->fullBit(oldp+34,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_spi));
        bufp->fullIData(oldp+35,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_spi),32);
        bufp->fullBit(oldp+36,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_can));
        bufp->fullSData(oldp+37,((0x00007fffU & vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)),15);
        bufp->fullBit(oldp+38,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_can));
        bufp->fullBit(oldp+39,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_can));
        bufp->fullIData(oldp+40,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_can),32);
        bufp->fullBit(oldp+41,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_pwm));
        bufp->fullBit(oldp+42,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_pwm));
        bufp->fullBit(oldp+43,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_pwm));
        bufp->fullIData(oldp+44,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_pwm),32);
        bufp->fullBit(oldp+45,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__o_psel_gyro));
        bufp->fullSData(oldp+46,((0x000003ffU & vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)),10);
        bufp->fullBit(oldp+47,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pready_gyro));
        bufp->fullBit(oldp+48,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_pslverr_gyro));
        bufp->fullIData(oldp+49,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_prdata_gyro),32);
        bufp->fullIData(oldp+50,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+51,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+52,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_write));
        bufp->fullSData(oldp+53,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_addr),15);
        bufp->fullIData(oldp+54,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+55,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+56,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullSData(oldp+57,((0x00007fffU & VL_SHIFTR_III(15,15,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_addr), 2U))),15);
        bufp->fullIData(oldp+58,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__dmem
                                 [(0x00007fffU & VL_SHIFTR_III(15,15,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+59,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_can_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullIData(oldp+60,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+61,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+62,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_write));
        bufp->fullSData(oldp+63,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_addr),10);
        bufp->fullIData(oldp+64,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+65,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+66,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullSData(oldp+67,((0x000003ffU & VL_SHIFTR_III(10,10,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_addr), 2U))),10);
        bufp->fullIData(oldp+68,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__dmem
                                 [(0x000003ffU & VL_SHIFTR_III(10,10,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+69,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_gyro_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullIData(oldp+70,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[0]),32);
        bufp->fullIData(oldp+71,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[1]),32);
        bufp->fullIData(oldp+72,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[2]),32);
        bufp->fullIData(oldp+73,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[3]),32);
        bufp->fullIData(oldp+74,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[4]),32);
        bufp->fullIData(oldp+75,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[5]),32);
        bufp->fullIData(oldp+76,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[6]),32);
        bufp->fullIData(oldp+77,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[7]),32);
        bufp->fullIData(oldp+78,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[8]),32);
        bufp->fullIData(oldp+79,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[9]),32);
        bufp->fullIData(oldp+80,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[10]),32);
        bufp->fullIData(oldp+81,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[11]),32);
        bufp->fullIData(oldp+82,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[12]),32);
        bufp->fullIData(oldp+83,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[13]),32);
        bufp->fullIData(oldp+84,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[14]),32);
        bufp->fullIData(oldp+85,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem[15]),32);
        bufp->fullIData(oldp+86,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+87,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+88,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_write));
        bufp->fullCData(oldp+89,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_addr),4);
        bufp->fullIData(oldp+90,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+91,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+92,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullCData(oldp+93,((0x0000000fU & VL_SHIFTR_III(4,4,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_addr), 2U))),4);
        bufp->fullIData(oldp+94,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__dmem
                                 [(0x0000000fU & VL_SHIFTR_III(4,4,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+95,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_i2c_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullBit(oldp+96,((0x000000ffU >= vlSelfRef.m_vlsit_apbdec_tb__DOT__m_paddr)));
        bufp->fullBit(oldp+97,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__w_slave_i2c_sel));
        bufp->fullBit(oldp+98,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__w_slave_spi_sel));
        bufp->fullBit(oldp+99,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__w_slave_can_sel));
        bufp->fullBit(oldp+100,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__w_slave_pwm_sel));
        bufp->fullBit(oldp+101,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_m_vlsit_apbdec__DOT__w_slave_gyro_sel));
        bufp->fullCData(oldp+102,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__state),2);
        bufp->fullBit(oldp+103,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__trans_done));
        bufp->fullIData(oldp+104,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__read_data),32);
        bufp->fullIData(oldp+105,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__wait_cnt),32);
        bufp->fullIData(oldp+106,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+107,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+108,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_write));
        bufp->fullCData(oldp+109,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_addr),8);
        bufp->fullIData(oldp+110,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+111,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+112,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullCData(oldp+113,((0x000000ffU & VL_SHIFTR_III(8,8,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_addr), 2U))),8);
        bufp->fullIData(oldp+114,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__dmem
                                  [(0x000000ffU & VL_SHIFTR_III(8,8,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+115,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_pwm_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullIData(oldp+116,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+117,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+118,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_write));
        bufp->fullSData(oldp+119,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_addr),12);
        bufp->fullIData(oldp+120,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+121,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+122,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullSData(oldp+123,((0x00000fffU & VL_SHIFTR_III(12,12,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_addr), 2U))),12);
        bufp->fullIData(oldp+124,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__dmem
                                  [(0x00000fffU & VL_SHIFTR_III(12,12,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+125,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_spi_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullIData(oldp+126,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_wait_cnt),32);
        bufp->fullBit(oldp+127,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_valid));
        bufp->fullBit(oldp+128,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_write));
        bufp->fullCData(oldp+129,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_addr),8);
        bufp->fullIData(oldp+130,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_wdata),32);
        bufp->fullCData(oldp+131,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_strb),4);
        bufp->fullCData(oldp+132,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_prot),3);
        bufp->fullCData(oldp+133,((0x000000ffU & VL_SHIFTR_III(8,8,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_addr), 2U))),8);
        bufp->fullIData(oldp+134,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__dmem
                                  [(0x000000ffU & VL_SHIFTR_III(8,8,32, (IData)(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_req_addr), 2U))]),32);
        bufp->fullIData(oldp+135,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_uart_slave_bfm__DOT__apb_slave_seq__DOT__i),32);
        bufp->fullBit(oldp+136,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_clk));
        bufp->fullBit(oldp+137,(vlSelfRef.m_vlsit_apbdec_tb__DOT__i_rst_n));
        bufp->fullCData(oldp+138,(vlSelfRef.m_vlsit_apbdec_tb__DOT__u_master_bfm__DOT__next_state),2);
    }
